import ProjectDescription

let workspace = Workspace(
    name: "SwiftUIFlow",
    projects: [
        "./"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
